#- name: Testing Handlers
#  hosts: all
#  tasks: 
#    - name: Install .Net 4.6.1
#      win_chocolatey:
#        name: dotnet4.6.1
#        state: present
#      notify:
#      - reboot server
#  handlers:
#  - name: reboot server
#    win_reboot:

- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks: 
    - name: Install flash player
      win_chocolatey:
        name: flashplayerppapi
        state: present
      notify:
      - reboot server
    
    - name: failing the task
      debug:
        msg: failing the task as testing purpose
      failed_when: true
      #ignore_errors: true

    - name: this is another task
      debug:
        msg: final task
      
  handlers:
  - name: reboot server
    win_reboot: