---
- name: Change User Permission
  hosts: all
  tasks: 
  - name: Grant FullControl AccessRule for user to a file
    win_acl:
      path: C:\Temp\test.conf
      user: user_mkchia
      rights: FullControl
      type: allow
      state: present
      inherit: ContainerInherit, ObjectInherit
      propagation: 'None'
...